import type { ResearchProfile } from "../ResearchTypes";
import type { DriverRegistryEntry, CategoryDefinition, WeightConfiguration } from "@/types/goldResearchConfig";

const US100_DRIVER_REGISTRY: DriverRegistryEntry[] = [
  { id: "us100-price", title: "US100 Price", shortTitle: "Price", category: "market-overview", order: 1, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Current US100 index price and daily movement." },
  { id: "us100-daily-pct", title: "Daily %", shortTitle: "Daily %", category: "market-overview", order: 2, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Daily percentage change." },
  { id: "us100-weekly-pct", title: "Weekly %", shortTitle: "Weekly %", category: "market-overview", order: 3, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Weekly percentage change." },
  { id: "us100-session-high", title: "Session High", shortTitle: "High", category: "market-overview", order: 4, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: false, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Current session high." },
  { id: "us100-session-low", title: "Session Low", shortTitle: "Low", category: "market-overview", order: 5, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: false, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Current session low." },
  { id: "us100-volume", title: "Volume", shortTitle: "Volume", category: "market-overview", order: 6, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: false, supportsHistory: true, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Current session volume." },
  { id: "us100-futures", title: "Futures", shortTitle: "Futures", category: "market-overview", order: 7, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "NQ futures pre-market movement." },

  { id: "us100-apple", title: "Apple", shortTitle: "AAPL", category: "mega-cap", order: 1, source: "twelvedata", enabled: true, weight: 1.2, defaultWeight: 1.2, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Apple Inc. price, change %, and index contribution." },
  { id: "us100-microsoft", title: "Microsoft", shortTitle: "MSFT", category: "mega-cap", order: 2, source: "twelvedata", enabled: true, weight: 1.2, defaultWeight: 1.2, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Microsoft Corp. price, change %, and index contribution." },
  { id: "us100-nvidia", title: "NVIDIA", shortTitle: "NVDA", category: "mega-cap", order: 3, source: "twelvedata", enabled: true, weight: 1.3, defaultWeight: 1.3, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "NVIDIA Corp. price, change %, and index contribution." },
  { id: "us100-amazon", title: "Amazon", shortTitle: "AMZN", category: "mega-cap", order: 4, source: "twelvedata", enabled: true, weight: 1.1, defaultWeight: 1.1, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Amazon.com Inc. price, change %, and index contribution." },
  { id: "us100-meta", title: "Meta", shortTitle: "META", category: "mega-cap", order: 5, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Meta Platforms Inc. price, change %, and index contribution." },
  { id: "us100-alphabet", title: "Alphabet", shortTitle: "GOOGL", category: "mega-cap", order: 6, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Alphabet Inc. price, change %, and index contribution." },
  { id: "us100-tesla", title: "Tesla", shortTitle: "TSLA", category: "mega-cap", order: 7, source: "twelvedata", enabled: true, weight: 0.9, defaultWeight: 0.9, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Tesla Inc. price, change %, and index contribution." },
  { id: "us100-broadcom", title: "Broadcom", shortTitle: "AVGO", category: "mega-cap", order: 8, source: "twelvedata", enabled: true, weight: 0.9, defaultWeight: 0.9, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Broadcom Inc. price, change %, and index contribution." },
  { id: "us100-amd", title: "AMD", shortTitle: "AMD", category: "mega-cap", order: 9, source: "twelvedata", enabled: true, weight: 0.8, defaultWeight: 0.8, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Advanced Micro Devices price, change %, and index contribution." },
  { id: "us100-netflix", title: "Netflix", shortTitle: "NFLX", category: "mega-cap", order: 10, source: "twelvedata", enabled: true, weight: 0.8, defaultWeight: 0.8, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Netflix Inc. price, change %, and index contribution." },

  { id: "us100-fed", title: "Federal Reserve", shortTitle: "Fed", category: "macro", order: 1, source: "news-api", enabled: true, weight: 1.3, defaultWeight: 1.3, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: true, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Federal Reserve policy stance, rate decisions, and forward guidance." },
  { id: "us100-dxy", title: "DXY", shortTitle: "DXY", category: "macro", order: 2, source: "twelvedata", enabled: true, weight: 1.1, defaultWeight: 1.1, supportsTrend: true, supportsHistory: true, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "US Dollar Index impact on US equities." },
  { id: "us100-treasury-yields", title: "Treasury Yields", shortTitle: "Yields", category: "macro", order: 3, source: "twelvedata", enabled: true, weight: 1.2, defaultWeight: 1.2, supportsTrend: true, supportsHistory: true, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "10Y and 2Y Treasury yield movements and yield curve." },
  { id: "us100-inflation", title: "Inflation", shortTitle: "Inflation", category: "macro", order: 4, source: "news-api", enabled: true, weight: 1.1, defaultWeight: 1.1, supportsTrend: false, supportsHistory: true, supportsEconomicSurprise: true, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "CPI, PCE, and inflation expectations." },
  { id: "us100-employment", title: "Employment", shortTitle: "Jobs", category: "macro", order: 5, source: "news-api", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: false, supportsHistory: true, supportsEconomicSurprise: true, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "NFP, unemployment rate, and labor market data." },
  { id: "us100-gdp", title: "GDP", shortTitle: "GDP", category: "macro", order: 6, source: "news-api", enabled: true, weight: 0.9, defaultWeight: 0.9, supportsTrend: false, supportsHistory: true, supportsEconomicSurprise: true, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "GDP growth rate and economic output." },
  { id: "us100-econ-calendar", title: "Economic Calendar", shortTitle: "Calendar", category: "macro", order: 7, source: "news-api", enabled: true, weight: 0.8, defaultWeight: 0.8, supportsTrend: false, supportsHistory: false, supportsEconomicSurprise: true, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Upcoming high-impact economic events." },

  { id: "us100-earnings-upcoming", title: "Upcoming Earnings", shortTitle: "Earnings", category: "earnings", order: 1, source: "news-api", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: false, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Upcoming mega-cap earnings announcements." },
  { id: "us100-earnings-estimate", title: "Earnings Estimate", shortTitle: "Estimate", category: "earnings", order: 2, source: "ai-analysis", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: false, supportsHistory: false, supportsEconomicSurprise: true, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Consensus EPS and revenue estimates." },
  { id: "us100-earnings-previous", title: "Previous Earnings", shortTitle: "Prev", category: "earnings", order: 3, source: "twelvedata", enabled: true, weight: 0.8, defaultWeight: 0.8, supportsTrend: false, supportsHistory: true, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Previous quarter earnings results." },
  { id: "us100-earnings-date", title: "Announcement Date", shortTitle: "Date", category: "earnings", order: 4, source: "news-api", enabled: true, weight: 0.7, defaultWeight: 0.7, supportsTrend: false, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Key earnings announcement dates." },
  { id: "us100-earnings-impact", title: "Market Impact", shortTitle: "Impact", category: "earnings", order: 5, source: "ai-analysis", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: false, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Expected market impact of upcoming earnings." },

  { id: "us100-ad", title: "Advance/Decline", shortTitle: "A/D", category: "breadth", order: 1, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: true, supportsHistory: true, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Advance/decline ratio for Nasdaq." },
  { id: "us100-new-highs", title: "New Highs", shortTitle: "Highs", category: "breadth", order: 2, source: "twelvedata", enabled: true, weight: 0.9, defaultWeight: 0.9, supportsTrend: true, supportsHistory: true, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Number of stocks making new 52-week highs." },
  { id: "us100-new-lows", title: "New Lows", shortTitle: "Lows", category: "breadth", order: 3, source: "twelvedata", enabled: true, weight: 0.9, defaultWeight: 0.9, supportsTrend: true, supportsHistory: true, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Number of stocks making new 52-week lows." },
  { id: "us100-breadth-score", title: "Breadth Score", shortTitle: "Score", category: "breadth", order: 4, source: "composite", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Composite market breadth score." },

  { id: "us100-vix", title: "VIX", shortTitle: "VIX", category: "volatility", order: 1, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: true, supportsHistory: true, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "CBOE Volatility Index — S&P 500 implied volatility." },
  { id: "us100-vxn", title: "VXN", shortTitle: "VXN", category: "volatility", order: 2, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: true, supportsHistory: true, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Nasdaq-100 implied volatility index." },
  { id: "us100-risk-rating", title: "Risk Rating", shortTitle: "Risk", category: "volatility", order: 3, source: "composite", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: false, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "Composite risk rating based on volatility metrics." },

  { id: "us100-qqq", title: "QQQ", shortTitle: "QQQ", category: "etf-flow", order: 1, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: true, supportsHistory: true, supportsEconomicSurprise: false, supportsInstitutionalFlow: true, supportsTechnicalBias: false, description: "Invesco QQQ Trust — ETF flow and price action." },
  { id: "us100-tqqq", title: "TQQQ", shortTitle: "TQQQ", category: "etf-flow", order: 2, source: "twelvedata", enabled: true, weight: 0.8, defaultWeight: 0.8, supportsTrend: true, supportsHistory: true, supportsEconomicSurprise: false, supportsInstitutionalFlow: true, supportsTechnicalBias: false, description: "ProShares UltraPro QQQ — 3x leveraged long." },
  { id: "us100-sqqq", title: "SQQQ", shortTitle: "SQQQ", category: "etf-flow", order: 3, source: "twelvedata", enabled: true, weight: 0.8, defaultWeight: 0.8, supportsTrend: true, supportsHistory: true, supportsEconomicSurprise: false, supportsInstitutionalFlow: true, supportsTechnicalBias: false, description: "ProShares UltraPro Short QQQ — 3x leveraged inverse." },
  { id: "us100-net-flow", title: "Net Flow", shortTitle: "Flow", category: "etf-flow", order: 4, source: "composite", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: false, supportsHistory: true, supportsEconomicSurprise: false, supportsInstitutionalFlow: true, supportsTechnicalBias: false, description: "Net ETF flow across QQQ ecosystem." },

  { id: "us100-sector-tech", title: "Technology", shortTitle: "Tech", category: "sector-rotation", order: 1, source: "twelvedata", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "XLK Technology Select Sector performance." },
  { id: "us100-sector-semi", title: "Semiconductors", shortTitle: "Semi", category: "sector-rotation", order: 2, source: "twelvedata", enabled: true, weight: 1.1, defaultWeight: 1.1, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "SMH VanEck Semiconductor ETF performance." },
  { id: "us100-sector-financials", title: "Financials", shortTitle: "Financials", category: "sector-rotation", order: 3, source: "twelvedata", enabled: true, weight: 0.8, defaultWeight: 0.8, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "XLF Financial Select Sector performance." },
  { id: "us100-sector-healthcare", title: "Healthcare", shortTitle: "Healthcare", category: "sector-rotation", order: 4, source: "twelvedata", enabled: true, weight: 0.7, defaultWeight: 0.7, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "XLV Health Care Select Sector performance." },
  { id: "us100-sector-energy", title: "Energy", shortTitle: "Energy", category: "sector-rotation", order: 5, source: "twelvedata", enabled: true, weight: 0.6, defaultWeight: 0.6, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "XLE Energy Select Sector performance." },
  { id: "us100-sector-industrials", title: "Industrials", shortTitle: "Industrials", category: "sector-rotation", order: 6, source: "twelvedata", enabled: true, weight: 0.6, defaultWeight: 0.6, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "XLI Industrial Select Sector performance." },
  { id: "us100-sector-utilities", title: "Utilities", shortTitle: "Utilities", category: "sector-rotation", order: 7, source: "twelvedata", enabled: true, weight: 0.5, defaultWeight: 0.5, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "XLU Utilities Select Sector performance." },
  { id: "us100-sector-consumer", title: "Consumer", shortTitle: "Consumer", category: "sector-rotation", order: 8, source: "twelvedata", enabled: true, weight: 0.7, defaultWeight: 0.7, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "XLY Consumer Discretionary and XLP Consumer Staples." },
  { id: "us100-sector-communication", title: "Communication", shortTitle: "Comms", category: "sector-rotation", order: 9, source: "twelvedata", enabled: true, weight: 0.7, defaultWeight: 0.7, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "XLC Communication Services Select Sector." },

  { id: "us100-trend", title: "Trend", shortTitle: "Trend", category: "technical", order: 1, source: "manual", enabled: true, weight: 1.2, defaultWeight: 1.2, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: true, description: "Primary trend direction and strength." },
  { id: "us100-momentum", title: "Momentum", shortTitle: "Momentum", category: "technical", order: 2, source: "manual", enabled: true, weight: 1.1, defaultWeight: 1.1, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: true, description: "RSI, MACD, and momentum indicators." },
  { id: "us100-moving-averages", title: "Moving Averages", shortTitle: "MAs", category: "technical", order: 3, source: "manual", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: true, description: "20/50/100/200 EMA and SMA relationships." },
  { id: "us100-support", title: "Support", shortTitle: "Support", category: "technical", order: 4, source: "manual", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: false, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: true, description: "Key support levels and zones." },
  { id: "us100-resistance", title: "Resistance", shortTitle: "Resistance", category: "technical", order: 5, source: "manual", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: false, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: true, description: "Key resistance levels and zones." },
  { id: "us100-market-structure", title: "Market Structure", shortTitle: "Structure", category: "technical", order: 6, source: "manual", enabled: true, weight: 1.1, defaultWeight: 1.1, supportsTrend: true, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: true, description: "BOS, MSS, liquidity sweeps, and structure shifts." },

  { id: "us100-ai-summary", title: "Institutional Summary", shortTitle: "AI Summary", category: "sentiment", order: 1, source: "ai-analysis", enabled: true, weight: 1.0, defaultWeight: 1.0, supportsTrend: false, supportsHistory: false, supportsEconomicSurprise: false, supportsInstitutionalFlow: false, supportsTechnicalBias: false, description: "AI-generated institutional summary of all US100 drivers." },
];

const US100_CATEGORY_DEFINITIONS: CategoryDefinition[] = [
  { id: "market-overview", title: "Market Overview", description: "US100 price action, session data, and futures.", driverIds: ["us100-price", "us100-daily-pct", "us100-weekly-pct", "us100-session-high", "us100-session-low", "us100-volume", "us100-futures"], defaultWeight: 10, icon: "Activity", color: "#3B82F6" },
  { id: "mega-cap", title: "Mega Cap Leadership", description: "Top 10 Nasdaq-100 constituents by weight — price, change %, and index contribution.", driverIds: ["us100-apple", "us100-microsoft", "us100-nvidia", "us100-amazon", "us100-meta", "us100-alphabet", "us100-tesla", "us100-broadcom", "us100-amd", "us100-netflix"], defaultWeight: 20, icon: "Crown", color: "#8B5CF6" },
  { id: "macro", title: "Macro Environment", description: "Federal Reserve, dollar, yields, inflation, employment, GDP, and economic calendar.", driverIds: ["us100-fed", "us100-dxy", "us100-treasury-yields", "us100-inflation", "us100-employment", "us100-gdp", "us100-econ-calendar"], defaultWeight: 25, icon: "Globe", color: "#F59E0B" },
  { id: "earnings", title: "Corporate Earnings", description: "Upcoming earnings, estimates, previous results, dates, and market impact.", driverIds: ["us100-earnings-upcoming", "us100-earnings-estimate", "us100-earnings-previous", "us100-earnings-date", "us100-earnings-impact"], defaultWeight: 8, icon: "FileText", color: "#10B981" },
  { id: "breadth", title: "Market Breadth", description: "Advance/decline, new highs/lows, and composite breadth score.", driverIds: ["us100-ad", "us100-new-highs", "us100-new-lows", "us100-breadth-score"], defaultWeight: 10, icon: "BarChart3", color: "#06B6D4" },
  { id: "volatility", title: "Volatility", description: "VIX, VXN, and composite risk rating.", driverIds: ["us100-vix", "us100-vxn", "us100-risk-rating"], defaultWeight: 10, icon: "Zap", color: "#EF4444" },
  { id: "etf-flow", title: "ETF Flow", description: "QQQ, TQQQ, SQQQ flow analysis and net institutional positioning.", driverIds: ["us100-qqq", "us100-tqqq", "us100-sqqq", "us100-net-flow"], defaultWeight: 10, icon: "ArrowUpDown", color: "#EC4899" },
  { id: "sector-rotation", title: "Sector Rotation", description: "Relative strength across 9 key sectors — technology, semiconductors, financials, healthcare, energy, industrials, utilities, consumer, communication.", driverIds: ["us100-sector-tech", "us100-sector-semi", "us100-sector-financials", "us100-sector-healthcare", "us100-sector-energy", "us100-sector-industrials", "us100-sector-utilities", "us100-sector-consumer", "us100-sector-communication"], defaultWeight: 7, icon: "Repeat", color: "#14B8A6" },
  { id: "technical", title: "Technical Analysis", description: "Trend, momentum, moving averages, support/resistance, and market structure.", driverIds: ["us100-trend", "us100-momentum", "us100-moving-averages", "us100-support", "us100-resistance", "us100-market-structure"], defaultWeight: 20, icon: "TrendingUp", color: "#6366F1" },
  { id: "sentiment", title: "Institutional Summary", description: "AI-generated synthesis of all US100 research drivers.", driverIds: ["us100-ai-summary"], defaultWeight: 5, icon: "BrainCircuit", color: "#A855F7" },
];

const US100_CATEGORY_WEIGHTS: WeightConfiguration = {
  categoryWeights: [
    { categoryId: "macro", weight: 25, driverWeights: [] },
    { categoryId: "mega-cap", weight: 20, driverWeights: [] },
    { categoryId: "technical", weight: 20, driverWeights: [] },
    { categoryId: "breadth", weight: 10, driverWeights: [] },
    { categoryId: "volatility", weight: 10, driverWeights: [] },
    { categoryId: "etf-flow", weight: 10, driverWeights: [] },
    { categoryId: "sentiment", weight: 5, driverWeights: [] },
  ],
};

export const US100_PROFILE: ResearchProfile = {
  asset: "us100",
  name: "US100",
  description: "Nasdaq-100 Institutional Research — mega cap leadership, macro environment, sector rotation, technical analysis, and institutional flow.",
  driverRegistry: US100_DRIVER_REGISTRY,
  categoryDefinitions: US100_CATEGORY_DEFINITIONS,
  categoryWeights: US100_CATEGORY_WEIGHTS,
  aiSystemPrompt: "You are an institutional analyst specialising in the Nasdaq-100 (US100). You receive pre-collected market data from multiple verified sources. Your job is to ANALYZE this data — NOT to search the internet. Do NOT invent prices or data. The data below is real, sourced, timestamped. Your job is to synthesize it into driver analysis, bias assessment, and a structured research report. Be concise. Do not hype trades. Do not give blind buy/sell calls. Separate bullish, bearish, neutral, and mixed drivers. Every section MUST reference the actual data provided. If data is marked 'Live Data Unavailable', set that field accordingly. Final verdict must be cautious and based on alignment between mega cap leadership, macro environment, sector rotation, technical structure, breadth, volatility, and ETF flows.",
  aiAnalystInstruction: "You are PRIMASTA TradeOS US100 Research, a professional Nasdaq-100 institutional research assistant. You receive pre-collected market data covering mega cap constituents (AAPL, MSFT, NVDA, AMZN, META, GOOGL, TSLA, AVGO, AMD, NFLX), macro environment (Fed, DXY, yields, inflation, employment, GDP), corporate earnings, market breadth, volatility (VIX, VXN), ETF flows (QQQ, TQQQ, SQQQ), sector rotation across 9 sectors, and technical analysis. Your job is to ANALYZE this data — NOT to search the internet. Do NOT invent prices or data. The data below is real, sourced, timestamped. Your job is to synthesize it into driver analysis, bias assessment, and a structured research report. Be concise. Do not hype trades. Do not give blind buy/sell calls. Separate bullish, bearish, neutral, and mixed drivers. Every section MUST reference the actual data provided. If data is marked 'Live Data Unavailable', set that field accordingly. Final verdict must be cautious and based on alignment between drivers.",
  impactLabels: {
    bullish: "Bullish US100",
    bearish: "Bearish US100",
    neutral: "Neutral",
    mixed: "Mixed-Wait",
  },
  overallBiasLabels: {
    bullish: "Bullish",
    bearish: "Bearish",
    neutral: "Neutral",
    mixed: "Mixed-Wait",
  },
  preTradeVerdictLabels: {
    tradeAllowed: "Trade Allowed",
    wait: "Wait",
    avoidBeforeNews: "Avoid Before Earnings",
    manageExisting: "Manage Existing Trade Only",
  },
  personalRule: "I only trade US100 when mega cap leadership, macro environment, technical structure, breadth, volatility, and ETF flows agree. If they do not agree, I wait.",
  supportedSections: [
    "Market Overview",
    "Mega Cap Leadership",
    "Macro Environment",
    "Corporate Earnings",
    "Market Breadth",
    "Volatility",
    "ETF Flow",
    "Sector Rotation",
    "Technical Analysis",
    "Institutional Summary",
  ],
  defaultDriverFields: {},
};
